name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    permissions:
      actions: read
      contents: read
      packages: none
      pull-requests: write
      security-events: none
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        sync-labels: true
        dot: true
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
